channels:
  - pytorch
dependencies:
  - python=3.11.*
  - numpy
  - scipy
  - astropy
  - matplotlib
  - h5py
  - cartopy
  - xarray
  - scikit-image
  - pytorch==2.5.*
  - pip
  - pip:
    - tqdm
    - hydra-core
    - pymap3d
    - metpy
