[project]
name = "gnss-tid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astropy>=6.1.6",
    "cartopy>=0.24.1",
    "dask>=2024.11.2",
    "h5netcdf>=1.4.1",
    "h5py>=3.12.1",
    "hydra-core>=1.3.2",
    "hydra-joblib-launcher>=1.2.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.3.0",
    "matplotlib>=3.9.2",
    "metpy>=1.6.3",
    "numpy>=2.1.3",
    "pymap3d>=3.1.0",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "torch>=2.5.1",
    "tqdm>=4.67.0",
    "xarray>=2024.10.0",
]

[project.scripts]
tid = "gnss_tid.main:main"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/gnss_tid"]
