defaults:
  - _self_
  - focus: timesmooth
  - event: 20150325_midnight_short
    # - debug

output_fn: "autofocus.h5"

sample:
  window: 4
  step: 2

hydra:
  job:
    chdir: True
  job_logging:
    formatters:
      simple:
        datefmt: '%Y-%m-%d %H:%M:%S'
        fmt: "[%(asctime)s][%(name)s][%(levelname)s] %(message)s"
