defaults:
  - client: sagan
  - _self_

block_size: 32
step_size: 8
nfft: 128
norm: patch
wave_type: spherical

n_trials: 1200
batch_size: 20
save: true

hydra:
  job_logging:
    formatters:
      simple:
        datefmt: '%Y-%m-%d %H:%M:%S'
        fmt: "[%(asctime)s][%(name)s][%(levelname)s] %(message)s"
